package tcg_test

import (
	"fmt"
	"strings"

	"github.com/msoap/tcg"
)

func ExampleBuffer_HLine() {
	b := tcg.NewBuffer(10, 10)
	b.HLine(0, 5, 10, tcg.Black)
	fmt.Println(strings.Join(b.Strings(), "\n"))

	// Output:
	// ..........
	// ..........
	// ..........
	// ..........
	// ..........
	// **********
	// ..........
	// ..........
	// ..........
	// ..........
}

func ExampleBuffer_VLine() {
	b := tcg.NewBuffer(10, 10)
	b.VLine(5, 0, 10, tcg.Black)
	fmt.Println(strings.Join(b.Strings(), "\n"))

	// Output:
	// .....*....
	// .....*....
	// .....*....
	// .....*....
	// .....*....
	// .....*....
	// .....*....
	// .....*....
	// .....*....
	// .....*....
}
